; n and d are functions of indices
(define (cont-frac-recur n d k)
  (if (= k 1)
    (/ (n 1) (d 1))
    (/ (n 1) (+ (d 1)
                (cont-frac-recur
                  (lambda (i) (n (+ i 1)))
                  (lambda (i) (d (+ i 1)))
                  (- k 1))))))
(define (cont-frac-iter n d k)
  (define (iter i)
    (if (= i k)
      (/ (n i) (d i))
      (/ (n i) (+ (d i)
                  (iter (inc i))))))
  (iter 1))

(define (cont-frac k)
  (display (cont-frac-recur (lambda (i) 1.0)
                            (lambda (i) 1.0)
                            k))
  (newline)
  (display (cont-frac-iter (lambda (i) 1.0)
                           (lambda (i) 1.0)
                           k)))